name: Deploy Create User Service

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
        

      # Paso 2: Configuración de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir la imagen de Docker
      - name: Build Docker image
        run: |  
          docker build -t myrepo/createserviceuser:${{ github.sha }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push myrepo/createserviceuser:${{ github.sha }}

      # Paso 5: Subir la imagen al repositorio de DockerHub
      - name: Push Docker image
        run: |
          docker push myrepo/createserviceuser:${{ github.sha }}

      # Paso 6: Desplegar a EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/your/private-key.pem ec2-user@52.206.177.25 << 'EOF'
            docker pull myrepo/createserviceuser:${{ github.sha }}
            docker stop createserviceuser || true
            docker rm createserviceuser || true
            docker run -d --name createserviceuser -p 80:80 myrepo/createserviceuser:${{ github.sha }}
          EOF
