version: '3.8'

services:
  createUser:
    build:
      context: ./createUser
    ports:
      - "3000:3000"
    env_file:
      - ./createUser/.env  # Cargar variables de entorno del microservicio CreateUser
    networks:
      - user-network
    volumes:
      - ./createUser:/app 
    restart: always

  deleteUser:
    build:
      context: ./deleteUser
    ports:
      - "3001:3001"
    env_file:
      - ./deleteUser/.env  # Cargar variables de entorno del microservicio DeleteUser
    networks:
      - user-network
    volumes:
      - ./deleteUser:/app 
    restart: always

networks:
  user-network:
    driver: bridge
