version: '3.8'

services:
  createUser:
    build:
      context: ./createUser
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET} 
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}  
    networks:
      - user-network
    volumes:
      - ./createUser:/app 
    restart: always

  deleteUser:
    build:
      context: ./deleteUser
    ports:
      - "3001:3001" 
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET} 
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
    networks:
      - user-network
    volumes:
      - ./deleteUser:/app 
    restart: always

networks:
  user-network:
    driver: bridge
