name: CI/CD Pipeline for listEvaluation Service

on:
  push:
    branches:
      - test

jobs:
  build-and-push-listEvaluation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t andy3dub/list-evaluation:latest -f ./backend/EvaluationsManagement/listEvaluation/Dockerfile ./backend/EvaluationsManagement/listEvaluation

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_A }}

      - name: Push Docker image to DockerHub
        run: |
          docker push andy3dub/list-evaluation:latest

  deploy-listEvaluation:
    needs: build-and-push-listEvaluation
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_LIST_EVALUATION }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY2_EVALUATIONS }}
          script: |
            sudo docker stop list-evaluation || true
            sudo docker rm list-evaluation || true
            sudo docker pull andy3dub/list-evaluation:latest
            sudo docker run -d -p 4008:4008 --name list-evaluation andy3dub/list-evaluation:latest