name: CI/CD Pipeline for listUser Service

on:
  push:
    branches:
      - test  

jobs:
  build-and-push-listUser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_J }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_J }}

      - name: Build and push listUser image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/UserManagement/listUser
          file: ./backend/UserManagement/listUser/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_J }}/list-user:v1

  deploy-listUser:
    needs: build-and-push-listUser
    runs-on: ubuntu-latest
    steps:
      - name: Deploy listUserUser to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_LIST_USER_QA }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY2_USERS }}
          script: |
            
            if ! command -v docker &> /dev/null
            then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
            fi

            
            sudo docker stop list-user || true
            sudo docker rm list-user || true

            
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME_J }}/list-user:v1

            
            sudo docker run -d --name list-user -p 3003:3003 \
              -e DB_URL="${{ secrets.DB_URL_MYSQL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME_J }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
              ${{ secrets.DOCKERHUB_USERNAME_J }}/list-user:v1