name: CI/CD Pipeline for Login Service

on:
  push:
    branches:
      - test  

jobs:
  build-and-push-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_j }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_j }}

      - name: Build and push login image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/login
          file: ./backend/login/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_J }}/login-service:v1

  deploy-login:
    needs: build-and-push-login
    runs-on: ubuntu-latest
    steps:
      - name: Deploy login service to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_LOGIN_IP_QA }}
          username: ubuntu  
          key: ${{ secrets.EC2_SSH_KEY2_LOGIN }}
          script: |
            
            
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            
            sudo docker stop login-service || true
            sudo docker rm login-service || true

            
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME_J }}/login-service:v1

            
            sudo docker run -d --name login-service -p 5000:5000 \
              -e DB_URL="mysql://admin_users:${{ secrets.DB_PASSWORD_MYSQL }}@${{ secrets.DB_HOST }}:3306/usersdb" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME_J }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
              -e CREATE_USER_SERVICE_URL="http://13.216.132.78:3000/users/register" \
              ${{ secrets.DOCKERHUB_USERNAME_J }}/login-service:v1
